In [2]:
import sys
list_comp = [ i**2 for i in range(1_000_000)]
print(sys.getsizeof(list_comp))

8448728


In [3]:
gen_expx 3= (i**2 for i in range(1_000_000))
# The `print(sys.getsizeof(gen_exp))` statement is calculating and printing the size of the generator expression `gen_exp` in bytes using the `sys.getsizeof()` function. This function returns the size of the object in memory. In this case, it is calculating the size of the generator expression without actually generating all the elements in the sequence.
print(sys.getsizeof(gen_exp)) 

SyntaxError: invalid syntax (2706252195.py, line 1)

In [ ]:
import time 
def timing_decorator(func):
    def wrapper(*args,**kwargs):
        start = time.time()
        result = func(*args,**kwargs)
        end = time.time()
        print(f"{func.__name__} took {end-start:.4f}s")
        return result
    return wrapper

@timing_decorator
def process_data(n):
    time.sleep(1)
    return "done"

process_data(100)

process_data took 1.0005s


'done'

In [ ]:
import numpy
a = numpy.array([[1, 2], [3, 4]])
b = numpy.array([[5, 6], [7, 8]])
c = a @ b  
c

array([[19, 22],
       [43, 50]])

In [ ]:
import numpy as np

def gradient_descent(X,y,learning_rate=0.01,epochs=1000):
    
    n_samples,n_features = X.shape
    b = np.zeros((n_samples,1))
    X_b = np.c_[b,X]
    
    weights = np.random.randn(n_features + 1) * 0.01
    
    for epoch in range(epochs):
        y_pred = X_b@weights
        error = y-y_pred
        gradient = - 2*(X_b.T@error)
        weights = weights - learning_rate*(gradient)
        
        if epoch%100==0:
            loss = np.mean(error**2)
            print(f"Epoch {epoch}: Loss = {loss:.0f}")
    return weights
    

In [ ]:

X = 2*np.random.rand(100,1)
y = 4+3*X[:,0] + np.random.randn(100)*0.5
gradient_descent(X,y,learning_rate=0.0001,epochs=1000)


Epoch 0: Loss = 48
Epoch 100: Loss = 5
Epoch 200: Loss = 4
Epoch 300: Loss = 4
Epoch 400: Loss = 4
Epoch 500: Loss = 4
Epoch 600: Loss = 4
Epoch 700: Loss = 4
Epoch 800: Loss = 4
Epoch 900: Loss = 4


array([-2.40441270e-03,  6.18821541e+00])

In [ ]:
import numpy as np

def train_test_split(X,y,test_size=0.2,random_state=None):
    if random_state is not None:
        np.random.seed(random_state)
    
    n_samples = len(X)
    indices = np.random.permutation(n_samples)
    test_count = int(n_samples * test_size)
    test_indices = indices[:test_count]
    train_indices = indices[test_count:]
    X_train = X[train_indices]
    X_test = X[test_indices]
    y_train = y[train_indices]
    y_test = y[test_indices]
    return X_train,y_train,X_test,y_test



In [ ]:
X=np.arange(100).reshape(50,2)
y = np.arange(50)
X_train,y_train,X_test,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier

numeric_features = ['age','income']
categorical_features = ['city','gender']

numeric_transformer = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
])

categorical_transformer = Pipeline([
    ('imputer',SimpleImputer(strategy='constant',fill_value='missing')),
    ('onehot',OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
    ('num',numeric_transformer,numeric_features),
    ('cat',categorical_transformer,categorical_features)
    ]
)

full_pipeline = Pipeline(steps=[
    ('preprocessor',preprocessor),
    ('classifier ',RandomForestClassifier(n_estimators=100))
])

# full_pipeline.fit(X_train,y_train)
# predications = full_pipeline.predict(X_test)

In [ ]:
import numpy as np

class StandardScaler:
    def __init__(self) -> None:
        self.mean = None
        self.std = None
    
    def fit(self,X):
        self.mean = np.mean(X,axis=0)
        self.std = np.std(X,axis=0)
        self.std[self.std==0]=1
        return self
    
    def transform(self,X):
        return (X-self.mean)/self.std
    
    def fit_transform(self,X):
        self.fit(X)
        return self.transform(X)
    

X = np.array([[1, 100], [2, 200], [3, 300], [4, 400], [5, 500]])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("Original data:")
print(X)
print("\nScaled data (mean=0, std=1):")
print(X_scaled)
print(f"\nMean of scaled: {X_scaled.mean(axis=0)}")
print(f"Std of scaled: {X_scaled.std(axis=0)}")

Original data:
[[  1 100]
 [  2 200]
 [  3 300]
 [  4 400]
 [  5 500]]

Scaled data (mean=0, std=1):
[[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]

Mean of scaled: [0. 0.]
Std of scaled: [1. 1.]


In [ ]:
colors = np.array(["red", "blue", "green", "red", "green", "blue"])


In [ ]:
import numpy as np
cate=np.unique(colors)
print({cat : idx for idx,cat in enumerate(cate)})

n_samples= len(colors)
n_cate = len(cate)

np.zeros((n_samples,n_cate))

{np.str_('blue'): 0, np.str_('green'): 1, np.str_('red'): 2}


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np

def one_hot_encoding(data):
    
    categories = np.unique(data)
    n_samples = len(data)
    n_categories = len(categories)
    
    cat_to_idx = {cat : idx for idx , cat in enumerate(categories)}
    # creating 2d matrix of n_sample and n_categories
    one_hot = np.zeros((n_samples,n_categories))
    
    for i , value in enumerate(data):
        one_hot[i,cat_to_idx[value]]=1
    
    return one_hot,categories


    

In [ ]:
encoded, categories = one_hot_encoding(colors)

print(f"Categories: {categories}")
print(f"Original: {colors}")
print(f"Encoded:\n{encoded}")

Categories: ['blue' 'green' 'red']
Original: ['red' 'blue' 'green' 'red' 'green' 'blue']
Encoded:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [ ]:
import numpy as np

def confusion_matrix_values(y_true,y_pred):
    TP = np.sum((y_true==1) & (y_pred==1))
    TN = np.sum((y_true==0)& (y_pred==0))
    FP = np.sum((y_true==0) * (y_pred==1))
    FN = np.sum((y_true==1) & (y_pred==0))
    return TP,TN,FP,FN
    
def accuracy(y_true,y_pred):
    TP, TN, FP, FN = confusion_matrix_values(y_true, y_pred)
    return (TP+TN)/(TP+TN+FP+FN)

def precision(y_true,y_pred):
    TP, TN, FP, FN = confusion_matrix_values(y_true, y_pred)
    if TP + FP==0:
        return 0
    return TP/(TP+FP)

def recall(y_true,y_pred):
    TP, TN, FP, FN = confusion_matrix_values(y_true, y_pred)
    if TP+FN ==0:
        return 0
    return TP/(TP+FN)

def f1_score(y_true,y_pred):
    prec = precision(y_true,y_pred)
    rec = recall(y_true,y_pred)
    return 2*(prec*rec)/prec+rec

y_true = np.array([1, 1, 1, 0, 0, 0, 1, 0, 1, 0])
y_pred = np.array([1, 1, 0, 0, 0, 1, 1, 0, 1, 0])

print(f"Accuracy:  {accuracy(y_true, y_pred):.2f}")
print(f"Precision: {precision(y_true, y_pred):.2f}")
print(f"Recall:    {recall(y_true, y_pred):.2f}")
print(f"F1 Score:  {f1_score(y_true, y_pred):.2f}")

Accuracy:  0.80
Precision: 0.80
Recall:    0.80
F1 Score:  2.40


In [ ]:
import pandas as pd 
import numpy as np
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()
data.keys()
X = data['data']
y= data['target']
df = pd.DataFrame(X,columns=data['feature_names'])
df['target']=y
df.tail()


,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1


In [ ]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [ ]:
df.isnull().sum().all()

np.False_

In [ ]:
df.duplicated().sum()


np.int64(0)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null

In [ ]:
df['worst radius'].mode()[0]

np.float64(12.36)

In [ ]:
arr = df['area error'].describe()
arr

count    569.000000
mean      40.337079
std       45.491006
min        6.802000
25%       17.850000
50%       24.530000
75%       45.190000
max      542.200000
Name: area error, dtype: float64

In [ ]:
q1,q3 = arr['25%'],arr['75%']
iqr = q3-q1
lower_bound = q1 - 1.5*iqr
upper_bound = q3 + 1.5*iqr

In [ ]:
df = df[(df['area error']>= lower_bound) & (df['area error'] <= upper_bound)]


In [ ]:
df['area error'].describe()

count    504.000000
mean      28.351087
std       16.835858
min        6.802000
25%       17.257500
50%       22.790000
75%       33.912500
max       83.500000
Name: area error, dtype: float64

In [ ]:
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
5,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,0.2087,0.07613,...,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440,0
6,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,0.1794,0.05742,...,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368,0
7,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,0.2196,0.07451,...,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510,0


In [ ]:
city= ['NY','LA','NY','SF','LA','SF','NY','LA','SF','NY']*51
df['city'] = city[:len(df)]

In [ ]:
df['city'].str.strip().str.lower().str.replace(' ','_')

1      ny
3      la
5      ny
6      sf
7      la
       ..
560    ny
561    ny
562    la
566    ny
568    sf
Name: city, Length: 504, dtype: str

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.datasets import load_diabetes
from sklearn.impute import SimpleImputer,KNNImputer


In [ ]:
data.keys()



dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
X = data.data
y = data.target

In [ ]:
df = pd.DataFrame(data = X , columns=data.feature_names)
df['target'] = y
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0


In [ ]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [ ]:
df.describe()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,0.627417
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,0.483918
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,0.000000
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,1.000000
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,1.000000
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,1.000000


In [ ]:
df['age'][3] = None

KeyError: 'age'

In [ ]:
imputer = SimpleImputer(strategy='median')
df[['age']] = imputer.fit_transform(df[['age']])


In [ ]:
df['age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
437    False
438    False
439    False
440    False
441    False
Name: age, Length: 442, dtype: bool

In [ ]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,0.005383,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0


In [ ]:
from sklearn.preprocessing import LabelEncoder

gender = ['male','female','lesbian', 'gay','guy', 'money','male','cat']*2
new_df = pd.DataFrame(data=gender,columns=['gender'])

In [ ]:
le = LabelEncoder()
new_df['gender'] =le.fit_transform(new_df['gender'])

In [ ]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,0.005383,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0


In [ ]:
df.drop(columns=['s1'],inplace=True)

In [ ]:
df.head()

,age,sex,bmi,bp,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,0.005383,-0.044642,-0.011595,-0.036656,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0


In [ ]:
X = df.drop(labels='target',axis=1)
y = df['target']
X.head()

,age,sex,bmi,bp,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,0.005383,-0.044642,-0.011595,-0.036656,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.015596,0.008142,-0.002592,-0.031988,-0.046641


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=False)

In [ ]:
X_train

,age,sex,bmi,bp,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,0.005383,-0.044642,-0.011595,-0.036656,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...
348,0.030811,-0.044642,-0.020218,-0.005670,-0.029497,0.078093,-0.039493,-0.010903,-0.001078
349,0.001751,0.050680,-0.057941,-0.043542,-0.047034,-0.098625,0.034309,-0.061176,-0.071494
350,-0.027310,0.050680,0.060618,0.107944,-0.017598,-0.002903,-0.002592,0.070207,0.135612
351,-0.085430,0.050680,-0.040696,-0.033213,-0.069580,-0.006584,-0.039493,-0.057803,-0.042499


In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)


In [ ]:
X_test

array([[26, 27],
       [78, 79],
       [60, 61],
       [90, 91],
       [34, 35],
       [96, 97],
       [52, 53],
       [50, 51],
       [64, 65],
       [38, 39]])

In [ ]:
X_test = scaler.transform(X_test)

In [ ]:
X_train.shape

(40, 2)

In [ ]:
X_test.shape

(10, 2)

In [ ]:
# 15 scaling 
from sklearn.preprocessing import MinMaxScaler,StandardScaler,RobustScaler,MaxAbsScaler
from sklearn.datasets import load_iris

X,y = load_iris(return_X_y=True)
X.shape

(150, 4)

In [ ]:
std_scaler = StandardScaler()
X_standardized = std_scaler.fit_transform(X)
print(f"Mean: {X_standardized.mean(axis=0).round(2)}")   # ~[0, 0, 0, 0]
print(f"Std:  {X_standardized.std(axis=0).round(2)}")    # ~[1, 1, 1, 1]


Mean: [-0. -0. -0. -0.]
Std:  [1. 1. 1. 1.]


# Min-Max Normalization

In [ ]:
import numpy as np

def normalize(data):
    data = np.array(data,dtype=np.float64)
    xMin = np.min(data,axis=0)
    xMax = np.max(data,axis=0)

    return (data - xMin)/(xMax-xMin) if np.all(xMax-xMin) >0 else 1
arr = np.array([ [10,20,30,40],[20,30,40,50]])
normalize(arr)

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [ ]:
def normalize_2d(data):
    """Normalize each column independently."""
    data = np.array(data, dtype=np.float64)
    mins = data.min(axis=0)
    maxs = data.max(axis=0)
    ranges = maxs - mins
    ranges[ranges == 0] = 1  # avoid division by zero
    return (data - mins) / ranges

normalize(arr)

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [ ]:


import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

df = pd.DataFrame({'color':['red','blue','green','blue','red']})

le = LabelEncoder()

le.fit_transform(df)

c:\Users\damod\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 0, 2])

In [3]:
import numpy as np
a = [0,0,0,0,0]
b = [3,4,5,6,7]

dot_product = np.dot(a,b)
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)
print('dot_product',dot_product)


dot_product 0


In [4]:
print(norm_a)

0.0
