In [1]:
import numpy as np

In [3]:
int_array = np.array([1, 2, 3, 4, 5],dtype=np.int32)
int_array 

array([1, 2, 3, 4, 5])

In [4]:
int_array = np.array([1, 2, 3, 4, 5],dtype=np.float32)

In [5]:
int_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [6]:
original_arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
original_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
arr_3d = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]],[[11, 12, 13, 14, 15],[16, 17, 18, 19, 20]]])

In [8]:
arr_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [10]:
linsapce_arr = np.linspace(0,1,10)
linsapce_arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
logspace_arr = np.logspace(0,2,10)
logspace_arr

array([  1.        ,   1.66810054,   2.7825594 ,   4.64158883,
         7.74263683,  12.91549665,  21.5443469 ,  35.93813664,
        59.94842503, 100.        ])

In [15]:
arrange_arr  = np.arange(0,10,2)
arrange_arr

array([0, 2, 4, 6, 8])

In [17]:
zero_arr = np.zeros((3,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
zero_array = np.zeros_like(original_arr)

zero_array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"Dimension of arr_1d: {arr_1d.ndim} , Shpae of arr_1d: {arr_1d.shape} , Size of arr_1d: {arr_1d.size}")

Dimension of arr_1d: 1 , Shpae of arr_1d: (5,) , Size of arr_1d: 5


In [25]:
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
first_row = arr[0]
first_element = arr[0,0]
first_element, first_row

(1, array([1, 2, 3, 4, 5]))

In [26]:
arr_3d = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]],[[11, 12, 13, 14, 15],[16, 17, 18, 19, 20]]])

In [28]:
arr_3d[0,0,0]

1

In [30]:
slice_arr = arr_3d[0,1]
slice_arr

array([ 6,  7,  8,  9, 10])

In [32]:
slice_arr = arr_3d[0,1,0:3]
slice_arr

array([6, 7, 8])

In [36]:
slice_arr = arr_3d[0::2]
slice_arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [55]:
arr_2d = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11,12,13,14,15]])
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [52]:
slice_arr = arr_2d[1::2]
slice_arr

array([[ 6,  7,  8,  9, 10]])

In [56]:
second_to_last = arr[-2::1]
second_to_last

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
sliced_arr = arr_2d[arr_2d > 5]
sliced_arr

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [62]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
scalar = 2

addition = arr1 + arr2
print("Addition:", addition)

subtraction = arr1 - arr2
print("Subtraction:", subtraction)

multiplication = arr1 * arr2
print("Multiplication:", multiplication)

division = arr1 / arr2
print("Division:", division)

modulus = arr1 % arr2
print("Modulus:", modulus)

exponential = arr1 ** arr2
print("Exponential:", exponential)

scalar_addition = arr1 + scalar
print("Scalar Addition:", scalar_addition)

scalar_subtraction = arr1 - scalar
print("Scalar Subtraction:", scalar_subtraction)

scalar_multiplication = arr1 * scalar
print("Scalar Multiplication:", scalar_multiplication)

scalar_division = arr1 / scalar
print("Scalar Division:", scalar_division)

scalar_modulus = arr1 % scalar
print("Scalar Modulus:", scalar_modulus)

scalar_exponential = arr1 ** scalar
print("Scalar Exponential:", scalar_exponential)


Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Modulus: [1 2 3 4 5]
Exponential: [      1     128    6561  262144 9765625]
Scalar Addition: [3 4 5 6 7]
Scalar Subtraction: [-1  0  1  2  3]
Scalar Multiplication: [ 2  4  6  8 10]
Scalar Division: [0.5 1.  1.5 2.  2.5]
Scalar Modulus: [1 0 1 0 1]
Scalar Exponential: [ 1  4  9 16 25]


In [65]:
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix_multiplication = np.dot(matrix_1,matrix_2)

In [66]:
matrix_multiplication

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### Append and Delete

In [2]:
original_arr = np.array([1,2,3])

original_arr = np.append(original_arr,[4,5,6])
original_arr

array([1, 2, 3, 4, 5, 6])

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

new_arr = np.delete(arr,[1,2,6,7])
new_arr

array([ 1,  4,  5,  6,  9, 10])

In [10]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

new_arr1 = np.delete(arr,1,axis=1)
new_arr2 = np.delete(arr,1,axis=0)

print("New Array 1:", new_arr1)
print("New Array 2:", new_arr2)

New Array 1: [[1 3]
 [4 6]
 [7 9]]
New Array 2: [[1 2 3]
 [7 8 9]]


## Aggregation Function and ufuncs

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

## Aggregation
mean_value = np.mean(arr)
print("Mean Value:", mean_value)

Mean Value: 5.5


In [13]:
median_value = np.median(arr)
variance_value = np.var(arr)
std_value = np.std(arr)

sum_value = np.sum(arr)
min_value = np.min(arr)
max_value = np.max(arr)
print("Median Value:", median_value)
print("Variance Value:", variance_value)
print("Standard Deviation Value:", std_value)
print("Sum Value:", sum_value)
print("Min Value:", min_value)
print("Max Value:", max_value)


Median Value: 5.5
Variance Value: 8.25
Standard Deviation Value: 2.8722813232690143
Sum Value: 55
Min Value: 1
Max Value: 10


In [14]:
## Universal Functions

sqrt_arr = np.sqrt(arr)
print("Square Root:", sqrt_arr)

exp_arr = np.exp(arr)
print("Exponential:", exp_arr)

Square Root: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
Exponential: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


## reshaping Array

The code you've selected is using four different methods to convert a 2D array (`arr_2d`) into a 1D array. Here's what each method does:

1. `arr_2d.reshape(-1)`: The `reshape` function gives a new shape to an array without changing its data. Here, the `-1` is used as a placeholder that means "adjust this dimension automatically to match the total size of the array".

2. `arr_2d.flatten()`: The `flatten` function returns a copy of the array collapsed into one dimension.

3. `arr_2d.ravel()`: The `ravel` function returns a contiguous flattened array. It's similar to `flatten`, but returns a view of the original array whenever possible. This means that if you modify the array returned by `ravel`, it may also modify the original array.

4. `arr_2d.reshape(9)`: This is similar to the first method, but here the new shape is explicitly specified as `9`. This will only work if `arr_2d` has exactly 9 elements.

The main difference between these methods is that `flatten` always returns a copy of the data, while `ravel` returns a view of the original array whenever possible. This can make `ravel` faster and less memory-intensive than `flatten`. The `reshape` function is more general and can be used to reshape an array to any shape, not just to flatten it.

In [16]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_1d = arr_2d.reshape(-1)
arr_1d_2 = arr_2d.flatten()
arr_1d_3 = arr_2d.ravel()
arr_1d_4 = arr_2d.reshape(9)

print("Reshape:", arr_1d)
print("Flatten:", arr_1d_2)
print("Ravel:", arr_1d_3)
print("Reshape:", arr_1d_4)

Reshape: [1 2 3 4 5 6 7 8 9]
Flatten: [1 2 3 4 5 6 7 8 9]
Ravel: [1 2 3 4 5 6 7 8 9]
Reshape: [1 2 3 4 5 6 7 8 9]


In [23]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

arr_2d = arr_1d.reshape(3,4)
arr_2d_1 = arr_1d.reshape(2,6)
print("Reshape:", arr_2d)
print("Reshape:", arr_2d_1)

arr_3d = arr_1d.reshape(2,3,2)
print("Reshape:", arr_3d)

Reshape: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshape: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Reshape: [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
!pip install skimage


In [27]:
from skimage import data 
image  = data.coins()
print("original image shape:", image.shape)

ModuleNotFoundError: No module named 'skimage'

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined_arr = np.concatenate((arr1,arr2),axis=0)
combined_arr

array([1, 2, 3, 4, 5, 6])

In [3]:
vertical_stack = np.vstack((arr1,arr2))
vertical_stack

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
hortizontal_stack = np.hstack((arr1,arr2))
hortizontal_stack

array([1, 2, 3, 4, 5, 6])

## spliting Array

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

split_arr = np.split(arr,5)
split_arr

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

## Alias View and Copy

**Alias**: An alias refers to multiple variables that all point to the same underlying NumPy array object. They share the same data in memory. Changes in the alias array will affect the original array.

**View**: The `.view()` method creates a new array object that looks at the same data as the original array but does not share the same identity. It provides a way to view the data differently or with different data types, but it still operates on the same underlying data.

**Copy**: A copy is a completely independent duplicate of a NumPy array. It has its own data in memory, and changes made to the copy will not affect the original array, and vice versa.


In [6]:
original_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
alias_arr = original_arr
alias_arr[0,0] = 100
print("Original Array:", original_arr)

Original Array: [[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [7]:
original_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
view_arr = original_arr.view()
view_arr[0,0] = 100
print("Original Array:", original_arr)

Original Array: [[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [8]:
original_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
copy_arr = original_arr.copy()
copy_arr[0,0] = 100
print("Original Array:", original_arr)

Original Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Sorting Array

In [10]:
data = np.array([1,2,6,2,9,1,5,0,8,9,10])
sorted_data = np.sort(data)
print("Sorted Data:", sorted_data)

reverse_sorted_data = np.sort(data)[::-1]
sorted_indices = np.argsort(data)
print("Reverse Sorted Data:", reverse_sorted_data)
print("Sorted Indices:", sorted_indices)

Sorted Data: [ 0  1  1  2  2  5  6  8  9  9 10]
Reverse Sorted Data: [10  9  9  8  6  5  2  2  1  1  0]
Sorted Indices: [ 7  0  5  1  3  6  2  8  4  9 10]


In [12]:
data = np.array([[1,2,3],[4,np.nan,6],[7,8,9]])
cleaned_data = data[~np.any(np.isnan(data),axis=1)]
print("Cleaned Data:", cleaned_data)
cleaned_data = np.nan_to_num(data)
print('cleaned_data',cleaned_data)

Cleaned Data: [[1. 2. 3.]
 [7. 8. 9.]]
cleaned_data [[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


## numpy for statistics analysis