In [1]:
import numpy as np

feature_vectors = np.array([25,50000,508])
magnitude = np.linalg.norm(feature_vectors)
unit_vector = feature_vectors/magnitude


In [2]:
v1  = np.array([1,2,3])
v2 = np.array([4,5,6])
dot_product = np.dot(v1,v2)
dot_product

np.int64(32)

In [3]:
weight =np.array([1,2])
feature = np.array([3.0,2.0])
predication = np.dot(weight,feature)
predication

np.float64(7.0)

In [6]:
import numpy as np

# Create a matrix (dataset: 3 samples, 4 features)
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(X.shape)  # (3, 4)

# Matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

c = A@B
d = np.matmul(A,B)
print(c,d)
a_T = A.T
a_inv = np.linalg.inv(A)
a_inv

(3, 4)
[[19 22]
 [43 50]] [[19 22]
 [43 50]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
import numpy as np
import torch

In [24]:
# NumPy tensors
scalar = np.array(5)         
vector = np.array([1, 2, 3])        
matrix = np.array([[1, 2], [3, 4]])  
tensor_3d = np.random.randn(3,3,2)
print(tensor_3d)

[[[ 0.74735933  0.52979085]
  [-0.69089088  0.7778801 ]
  [ 0.91682743  0.73174675]]

 [[ 0.69941847 -1.03743265]
  [ 0.01112775 -2.20451184]
  [-2.39946208  0.3702971 ]]

 [[ 0.8320525  -1.20931615]
  [-1.02275912 -0.0391012 ]
  [-0.68203476  1.35579397]]]


In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6])
dot1 = np.dot(a,b)
dot2 = a@b 
dot3 = np.sum(a*b)

def cosine_similarity(a,b):
    return np.dot(a,b)/np.linalg.norm(a)*np.linalg.norm(b)

predication = np.dot(a,b)+dot1

In [27]:
dot1

np.int64(32)

In [26]:
predication

np.int64(64)

In [ ]:
def compute_normal(p1,p2,p3):
    x = p2-p1
    y = p3-p1
    normal = np.cross(x,y)
    return normal/np.linalg.norm(normal)

In [29]:
A = np.array([[4,2],[3,1]])
det_A = np.linalg.det(A)
det_A

np.float64(-2.0)

In [30]:
if np.abs(det_A)>1e-10:
    A_inv = np.linalg.inv(A)
    print('matrix is invertible')
else:
    print("matrix is singular")

matrix is invertible


In [35]:
X = np.random.randn(10,3)
print(X)
cov = np.cov(X.T)
det_cov = np.linalg.det(cov)
det_cov

[[-0.20912327 -0.50316988 -0.80677224]
 [-1.16760337 -1.2603981  -1.00354876]
 [ 2.69347899  1.40025934 -0.52906562]
 [-1.37065148 -0.60104051  1.01143   ]
 [-0.8658438   0.2895589   0.95569729]
 [ 0.0553077  -0.10873327 -0.52323786]
 [ 0.29779539 -0.03996048  1.16122922]
 [ 0.88168125 -0.05485275 -0.8034043 ]
 [ 1.62930257  2.58429535  0.50074355]
 [ 1.96013093 -1.83859413 -0.97685249]]


np.float64(1.237136132453161)

In [15]:
import numpy as np
A = np.array([[4,2],[1,3]])
eignvalues,eignvector = np.linalg.eig(A)

In [20]:
v = eignvector[:,0]
print(v)
lam = eignvalues[0]
np.allclose(A@v,lam*v)
A@v

[0.89442719 0.4472136 ]


array([4.47213595, 2.23606798])

In [22]:
not_eign = np.array([1,2])
print(A@not_eign,lam*not_eign)

[8 7] [ 5. 10.]


In [25]:
X=np.random.randn(100,5)
x_centered = X-X.mean(axis=0)
cov_matrix = np.cov(x_centered.T)

In [36]:
eignvalues,eignvector = np.linalg.eigh(cov_matrix)
idx = eignvalues.argsort()[::-1]
eignvalues = eignvalues[idx]
eignvector = eignvector[idx]

In [37]:
pc1 = eignvector[:,0]
pc1

array([ 0.36844395, -0.61799403,  0.08242019, -0.00366751,  0.68958386])

In [40]:
eignvector

array([[ 0.36844395, -0.04020381,  0.70859846,  0.31519129,  0.51105321],
       [-0.61799403,  0.21759873,  0.24559335,  0.65618236, -0.28256465],
       [ 0.08242019,  0.85676627,  0.29234151, -0.3848192 , -0.16002842],
       [-0.00366751,  0.45101776, -0.55993349,  0.32182042,  0.61601593],
       [ 0.68958386,  0.11648596, -0.1964257 ,  0.46735957, -0.50388204]])

In [41]:
eignvector[:,1]

array([-0.04020381,  0.21759873,  0.85676627,  0.45101776,  0.11648596])

In [42]:
d = np.array([2,3,4])
D = np.diag(d)
D

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [43]:
X = np.random.randn(100,5)
y = np.random.randn(100)
lambda_reg = 0.1
XtX = X.T @X 
XtX_regularized = XtX + lambda_reg*np.eye(5)
weights = np.linalg.inv(XtX_regularized)@X.T@y
weights

array([ 0.07768378,  0.15637099, -0.06377392,  0.0209799 ,  0.05934937])

In [ ]:
def residual_block(x,transform_fn):
    return x+transform_fn(x)


In [47]:
import numpy as np
vector = np.array([[3,4],[1,0],[5,12]])
norm = np.linalg.norm(vector,axis=1,keepdims=True)
unit_vector = vector/norm
unit_vector


array([[0.6       , 0.8       ],
       [1.        , 0.        ],
       [0.38461538, 0.92307692]])

In [55]:
def cosine_similarity(a,b):
    a_unit = a/np.linalg.norm(a)
    b_unit = b/np.linalg.norm(b)
    return np.dot(a_unit,b_unit)

a = np.array([3,4])
b = np.array(object=[1301,10])
cosine_similarity(a,b)

np.float64(0.6061312110101964)

In [ ]:
import numpy as np
from scipy.stats import ortho_group

theta = np.pi/4
q_rotation = np.array([[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]])
print(np.allclose(q_rotation.T @ q_rotation,np.eye(2)))

True


In [4]:
np.linalg.det(q_rotation)

np.float64(1.0)

In [6]:
x = np.array([3,4])
qx = q_rotation@x 
print(np.linalg.norm(x))
print(np.linalg.norm(qx))

5.0
5.0


In [8]:
q_random = ortho_group.rvs(dim=3)
q_random

array([[-0.00334649, -0.32418434, -0.94598801],
       [ 0.66658942, -0.70588715,  0.23954514],
       [ 0.74541757,  0.62978396, -0.21846009]])

In [9]:
A = np.random.randn(4,3)
Q , R  = np.linalg.qr(A)
Q

array([[-0.59678789, -0.01100105, -0.73518375],
       [ 0.71054088, -0.41680112, -0.56686643],
       [ 0.36310219,  0.64969241, -0.01264787],
       [ 0.08445512,  0.63565367, -0.37149338]])

In [10]:
R 

array([[-1.3348244 , -1.83868415, -0.90879281],
       [ 0.        , -0.94955069, -1.00223607],
       [ 0.        ,  0.        , -1.23811445]])

In [11]:
Q.T @ Q

array([[ 1.00000000e+00, -3.00153694e-17,  1.71495566e-16],
       [-3.00153694e-17,  1.00000000e+00,  1.08949375e-16],
       [ 1.71495566e-16,  1.08949375e-16,  1.00000000e+00]])

In [12]:
np.linalg.trace(R)

np.float64(-3.5224895439394404)

In [13]:
A = np.array([[1,2],[3,4]])
rank_a = np.linalg.matrix_rank(A)
rank_a

np.int64(2)

In [1]:
import numpy as np

In [2]:
x = np.random.randn(100,10)
rank_x = np.linalg.matrix_rank(x)
rank_x

np.int64(10)

In [3]:
x_redundant = np.column_stack([x,x[:,0]*2])
x_redundant.shape

(100, 11)

In [4]:
def check_full_rank(x):
    n_samples,n_features = x.shape
    rank = np.linalg.matrix_rank(x)
    if rank<n_features:
         print(f"Warning: Rank {rank} < {n_features} features. Multicollinearity present.")
    return rank==n_features

check_full_rank(x_redundant)

np.False_

In [14]:
A = np.array([[1,2],[2,3]])
U,s,Vt = np.linalg.svd(A)
print(U,'\n',s,'\n',Vt)

[[-0.52573111 -0.85065081]
 [-0.85065081  0.52573111]] 
 [4.23606798 0.23606798] 
 [[-0.52573111 -0.85065081]
 [ 0.85065081 -0.52573111]]


In [ ]:
np.allclose(U.T@U , np.eye(2))

True

: 

In [ ]:
def low_rank_approx(A,k):
    U,s,Vt = np.linalg.svd(a,full_matrices=True)
    return U[:,:k] @np.diag(s)

In [12]:
import numpy as np 

def gaussian_elimination(A,b):
    n  = len(b)
    Ab = np.concatenate([A,b.reshape(-1,1)],axis=1).astype(float)
    for i in range(n):
        # pivot method ( replace max row element with first row )
        max_row = i
        for rem_row in range(i+1,n):
            if abs(Ab[rem_row,i]>abs(Ab[max_row,i])):
                max_row = max_row
        Ab[i],Ab[max_row] = Ab[max_row].copy(),Ab[i].copy()
        # elimination method
        for j in range(i+1,n):
            factor = Ab[j,i]/Ab[i,i]
            Ab[j] = Ab[j]-factor*Ab[i]
        # back substitution 
        
        x = np.zeros(n)
        for i in range(n-1,-1,-1):
            s = 0
            for j in range(i+1,n):
                s+=Ab[i,j]*x[j]
            x[i] = (Ab[i,-1]- s)/Ab[i,i]
        return x


In [15]:
A = np.array([
    [2, 1, -1],
    [0, 1,  3],
    [0, 0,  2]
], dtype=float)

b = np.array([8,5,4])
gaussian_elimination(A,b)


array([ 5.5, -1. ,  2. ])

In [16]:
np.linalg.solve(A,b)

array([ 5.5, -1. ,  2. ])

In [6]:
import numpy as np
from scipy.linalg import null_space

A1 = np.array([[2, 1], [1, 3]])
b1 = np.array([4, 5]) 
x1 = np.linalg.solve(A1,b1)
print("unique solution :",x1)

A2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2 equations, 3 unknowns
b2 = np.array([1, 2])

x_particular , residuals,rank,s = np.linalg.lstsq(A2,b2)
null = null_space(A2)
print("Null space basis :\n",null)

unique solution : [1.4 1.2]
Null space basis :
 [[ 0.40824829]
 [-0.81649658]
 [ 0.40824829]]


In [4]:
import numpy as np
from scipy.linalg import lu,lu_factor,lu_solve

A = np.array([[2,1,1],[4,3,3],[8,7,9]],dtype=float)
b = np.array([4,10,24])
P,L,U = lu(A)
print("L:\n", L)
print("U:\n", U)
print("P @ L @ U:\n", P @ L @ U) 
lu_factored ,piv = lu_factor(A)
b1 = np.array([4,10,24])
b2 = np.array([1,2,3])
x1 = lu_solve((lu_factored,piv),b1)
x2 = lu_solve((lu_factored,piv),b2)

print('x1',x1)
print('x2',x2)


L:
 [[1.         0.         0.        ]
 [0.25       1.         0.        ]
 [0.5        0.66666667 1.        ]]
U:
 [[ 8.          7.          9.        ]
 [ 0.         -0.75       -1.25      ]
 [ 0.          0.         -0.66666667]]
P @ L @ U:
 [[2. 1. 1.]
 [4. 3. 3.]
 [8. 7. 9.]]
x1 [1. 1. 1.]
x2 [ 0.5  0.5 -0.5]


In [5]:
det_A = np.prod(np.diag(lu_factored)) * (-1)**(np.sum(piv != np.arange(len(piv))))
print("det(A):", det_A)

det(A): 4.000000000000002


In [6]:
def solve_lower(L, b):
    """Forward substitution for Ly = b"""
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = (b[i] - L[i, :i] @ y[:i]) / L[i, i]
    return y

def solve_upper(U, y):
    """Back substitution for Ux = y"""
    n = len(y)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - U[i, i+1:] @ x[i+1:]) / U[i, i]
    return x