In [1]:
import numpy as np

feature_vectors = np.array([25,50000,508])
magnitude = np.linalg.norm(feature_vectors)
unit_vector = feature_vectors/magnitude


In [2]:
v1  = np.array([1,2,3])
v2 = np.array([4,5,6])
dot_product = np.dot(v1,v2)
dot_product

np.int64(32)

In [3]:
weight =np.array([1,2])
feature = np.array([3.0,2.0])
predication = np.dot(weight,feature)
predication

np.float64(7.0)

In [6]:
import numpy as np

# Create a matrix (dataset: 3 samples, 4 features)
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(X.shape)  # (3, 4)

# Matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

c = A@B
d = np.matmul(A,B)
print(c,d)
a_T = A.T
a_inv = np.linalg.inv(A)
a_inv

(3, 4)
[[19 22]
 [43 50]] [[19 22]
 [43 50]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
import numpy as np
import torch

In [24]:
# NumPy tensors
scalar = np.array(5)         
vector = np.array([1, 2, 3])        
matrix = np.array([[1, 2], [3, 4]])  
tensor_3d = np.random.randn(3,3,2)
print(tensor_3d)

[[[ 0.74735933  0.52979085]
  [-0.69089088  0.7778801 ]
  [ 0.91682743  0.73174675]]

 [[ 0.69941847 -1.03743265]
  [ 0.01112775 -2.20451184]
  [-2.39946208  0.3702971 ]]

 [[ 0.8320525  -1.20931615]
  [-1.02275912 -0.0391012 ]
  [-0.68203476  1.35579397]]]


In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6])
dot1 = np.dot(a,b)
dot2 = a@b 
dot3 = np.sum(a*b)

def cosine_similarity(a,b):
    return np.dot(a,b)/np.linalg.norm(a)*np.linalg.norm(b)

predication = np.dot(a,b)+dot1

In [27]:
dot1

np.int64(32)

In [26]:
predication

np.int64(64)

In [ ]:
def compute_normal(p1,p2,p3):
    x = p2-p1
    y = p3-p1
    normal = np.cross(x,y)
    return normal/np.linalg.norm(normal)

In [29]:
A = np.array([[4,2],[3,1]])
det_A = np.linalg.det(A)
det_A

np.float64(-2.0)

In [30]:
if np.abs(det_A)>1e-10:
    A_inv = np.linalg.inv(A)
    print('matrix is invertible')
else:
    print("matrix is singular")

matrix is invertible


In [35]:
X = np.random.randn(10,3)
print(X)
cov = np.cov(X.T)
det_cov = np.linalg.det(cov)
det_cov

[[-0.20912327 -0.50316988 -0.80677224]
 [-1.16760337 -1.2603981  -1.00354876]
 [ 2.69347899  1.40025934 -0.52906562]
 [-1.37065148 -0.60104051  1.01143   ]
 [-0.8658438   0.2895589   0.95569729]
 [ 0.0553077  -0.10873327 -0.52323786]
 [ 0.29779539 -0.03996048  1.16122922]
 [ 0.88168125 -0.05485275 -0.8034043 ]
 [ 1.62930257  2.58429535  0.50074355]
 [ 1.96013093 -1.83859413 -0.97685249]]


np.float64(1.237136132453161)