In [1]:
import numpy as np

A= np.array([(1,2,3),[4,5,6]])
B = np.array([(7,8,9),(10,11,12)])

C = A+B
C

array([[ 8, 10, 12],
       [14, 16, 18]])

In [3]:
c = A-B
c 

array([[-6, -6, -6],
       [-6, -6, -6]])

In [5]:
c = A*B
c 

array([[ 7, 16, 27],
       [40, 55, 72]])

In [6]:
A_transpose = A.T

In [7]:
A_transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

(X.T@X)^-1@X.T@y


In [11]:
v = np.array([1,2])
l2_norm = np.linalg.norm(v,ord=2)
l1_norm = np.linalg.norm(v,ord=1)
linf_norm = np.linalg.norm(v,ord=np.inf)

In [12]:
print(l2_norm)
print(l1_norm)
print(linf_norm)

2.23606797749979
3.0
2.0


In [13]:
v1 = np.array([1,1])
v2 = np.array([1,-1])
dot_product = np.dot(v1, v2)
print(dot_product)

0


In [14]:
theta = np.pi/4
q = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
q_t_q = q.T @ q

In [15]:
print(q_t_q)
print(q)

[[ 1.00000000e+00 -4.26642159e-17]
 [-4.26642159e-17  1.00000000e+00]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [16]:
identity = np.eye(2)
print(identity)

[[1. 0.]
 [0. 1.]]


In [18]:
print(np.round(q,2))
print(np.round(q_t_q,2))
print(np.allclose(q_t_q, identity))

[[ 0.71 -0.71]
 [ 0.71  0.71]]
[[ 1. -0.]
 [-0.  1.]]
True
