In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [8]:
def initialize_parmeters(layer_dims):
    np.random.seed(3)
    parametrs  = {}
    L = len(layer_dims)
    print(L)
    for l in range(1,L):
        parametrs['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1]) * 0.01
        parametrs['b' + str(l)] = np.zeros((layer_dims[l], 1))
        print(parametrs['W' + str(l)])
        print(parametrs['b' + str(l)])

In [12]:
initialize_parmeters([3,2,1])

3
[[ 0.01788628  0.0043651   0.00096497]
 [-0.01863493 -0.00277388 -0.00354759]]
[[0.]
 [0.]]
[[-0.00082741 -0.00627001]]
[[0.]]
