In [2]:
import numpy as np

In [3]:
int_array = np.array([1, 2, 3, 4, 5],dtype=np.int32)
int_array 

array([1, 2, 3, 4, 5])

In [4]:
int_array = np.array([1, 2, 3, 4, 5],dtype=np.float32)

In [5]:
int_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [6]:
original_arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
original_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
arr_3d = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]],[[11, 12, 13, 14, 15],[16, 17, 18, 19, 20]]])

In [8]:
arr_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [10]:
linsapce_arr = np.linspace(0,1,10)
linsapce_arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
logspace_arr = np.logspace(0,2,10)
logspace_arr

array([  1.        ,   1.66810054,   2.7825594 ,   4.64158883,
         7.74263683,  12.91549665,  21.5443469 ,  35.93813664,
        59.94842503, 100.        ])

In [15]:
arrange_arr  = np.arange(0,10,2)
arrange_arr

array([0, 2, 4, 6, 8])

In [17]:
zero_arr = np.zeros((3,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
zero_array = np.zeros_like(original_arr)

zero_array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"Dimension of arr_1d: {arr_1d.ndim} , Shpae of arr_1d: {arr_1d.shape} , Size of arr_1d: {arr_1d.size}")

Dimension of arr_1d: 1 , Shpae of arr_1d: (5,) , Size of arr_1d: 5


In [25]:
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
first_row = arr[0]
first_element = arr[0,0]
first_element, first_row

(1, array([1, 2, 3, 4, 5]))

In [26]:
arr_3d = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]],[[11, 12, 13, 14, 15],[16, 17, 18, 19, 20]]])

In [28]:
arr_3d[0,0,0]

1

In [30]:
slice_arr = arr_3d[0,1]
slice_arr

array([ 6,  7,  8,  9, 10])

In [32]:
slice_arr = arr_3d[0,1,0:3]
slice_arr

array([6, 7, 8])

In [36]:
slice_arr = arr_3d[0::2]
slice_arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [55]:
arr_2d = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11,12,13,14,15]])
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [52]:
slice_arr = arr_2d[1::2]
slice_arr

array([[ 6,  7,  8,  9, 10]])

In [56]:
second_to_last = arr[-2::1]
second_to_last

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
sliced_arr = arr_2d[arr_2d > 5]
sliced_arr

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [62]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
scalar = 2

addition = arr1 + arr2
print("Addition:", addition)

subtraction = arr1 - arr2
print("Subtraction:", subtraction)

multiplication = arr1 * arr2
print("Multiplication:", multiplication)

division = arr1 / arr2
print("Division:", division)

modulus = arr1 % arr2
print("Modulus:", modulus)

exponential = arr1 ** arr2
print("Exponential:", exponential)

scalar_addition = arr1 + scalar
print("Scalar Addition:", scalar_addition)

scalar_subtraction = arr1 - scalar
print("Scalar Subtraction:", scalar_subtraction)

scalar_multiplication = arr1 * scalar
print("Scalar Multiplication:", scalar_multiplication)

scalar_division = arr1 / scalar
print("Scalar Division:", scalar_division)

scalar_modulus = arr1 % scalar
print("Scalar Modulus:", scalar_modulus)

scalar_exponential = arr1 ** scalar
print("Scalar Exponential:", scalar_exponential)


Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Modulus: [1 2 3 4 5]
Exponential: [      1     128    6561  262144 9765625]
Scalar Addition: [3 4 5 6 7]
Scalar Subtraction: [-1  0  1  2  3]
Scalar Multiplication: [ 2  4  6  8 10]
Scalar Division: [0.5 1.  1.5 2.  2.5]
Scalar Modulus: [1 0 1 0 1]
Scalar Exponential: [ 1  4  9 16 25]


In [65]:
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix_multiplication = np.dot(matrix_1,matrix_2)

In [66]:
matrix_multiplication

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### Append and Delete

In [ ]:
original_arr = npm