In [1]:
import sys
list_comp = [ i**2 for i in range(1_000_000)]
print(sys.getsizeof(list_comp))

8448728


In [2]:
gen_exp= (i**2 for i in range(1_000_000))
print(sys.getsizeof(gen_exp))

200


In [3]:
import time 
def timing_decorator(func):
    def wrapper(*args,**kwargs):
        start = time.time()
        result = func(*args,**kwargs)
        end = time.time()
        print(f"{func.__name__} took {end-start:.4f}s")
        return result
    return wrapper

@timing_decorator
def process_data(n):
    time.sleep(1)
    return "done"

process_data(100)

process_data took 1.0011s


'done'

In [7]:
import numpy
a = numpy.array([[1, 2], [3, 4]])
b = numpy.array([[5, 6], [7, 8]])
c = a @ b  
c

array([[19, 22],
       [43, 50]])

In [69]:
import numpy as np

def gradient_descent(X,y,learning_rate=0.01,epochs=1000):
    
    n_samples,n_features = X.shape
    b = np.zeros((n_samples,1))
    X_b = np.c_[b,X]
    
    weights = np.random.randn(n_features + 1) * 0.01
    
    for epoch in range(epochs):
        y_pred = X_b@weights
        error = y-y_pred
        gradient = - 2*(X_b.T@error)
        weights = weights - learning_rate*(gradient)
        
        if epoch%100==0:
            loss = np.mean(error**2)
            print(f"Epoch {epoch}: Loss = {loss:.0f}")
    return weights
    

In [76]:

X = 2*np.random.rand(100,1)
y = 4+3*X[:,0] + np.random.randn(100)*0.5
gradient_descent(X,y,learning_rate=0.0001,epochs=1000)


Epoch 0: Loss = 54
Epoch 100: Loss = 4
Epoch 200: Loss = 4
Epoch 300: Loss = 4
Epoch 400: Loss = 4
Epoch 500: Loss = 4
Epoch 600: Loss = 4
Epoch 700: Loss = 4
Epoch 800: Loss = 4
Epoch 900: Loss = 4


array([0.01672572, 5.97003522])

In [23]:
import numpy as np

def train_test_split(X,y,test_size=0.2,random_state=None):
    if random_state is not None:
        np.random.seed(random_state)
    
    n_samples = len(X)
    indices = np.random.permutation(n_samples)
    test_count = int(n_samples * test_size)
    test_indices = indices[:test_count]
    train_indices = indices[test_count:]
    X_train = X[train_indices]
    X_test = X[test_indices]
    y_train = y[train_indices]
    y_test = y[test_indices]
    return X_train,y_train,X_test,y_test



In [24]:
X=np.arange(100).reshape(50,2)
y = np.arange(50)
X_train,y_train,X_test,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier

numeric_features = ['age','income']
categorical_features = ['city','gender']

numeric_transformer = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
])

categorical_transformer = Pipeline([
    ('imputer',SimpleImputer(strategy='constant',fill_value='missing')),
    ('onehot',OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
    ('num',numeric_transformer,numeric_features),
    ('cat',categorical_transformer,categorical_features)
    ]
)

full_pipeline = Pipeline(steps=[
    ('preprocessor',preprocessor),
    ('classifier ',RandomForestClassifier(n_estimators=100))
])

full_pipeline.fit(X_train,y_train)
predications = full_pipeline.predict(X_test)

ValueError: Specifying the columns using strings is only supported for dataframes.

In [2]:
import numpy as np

class StandardScaler:
    def __init__(self) -> None:
        self.mean = None
        self.std = None
    
    def fit(self,X):
        self.mean = np.mean(X,axis=0)
        self.std = np.std(X,axis=0)
        self.std[self.std==0]=1
        return self
    
    def transform(self,X):
        return (X-self.mean)/self.std
    
    def fit_transform(self,X):
        self.fit(X)
        return self.transform(X)
    

X = np.array([[1, 100], [2, 200], [3, 300], [4, 400], [5, 500]])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("Original data:")
print(X)
print("\nScaled data (mean=0, std=1):")
print(X_scaled)
print(f"\nMean of scaled: {X_scaled.mean(axis=0)}")
print(f"Std of scaled: {X_scaled.std(axis=0)}")

Original data:
[[  1 100]
 [  2 200]
 [  3 300]
 [  4 400]
 [  5 500]]

Scaled data (mean=0, std=1):
[[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]

Mean of scaled: [0. 0.]
Std of scaled: [1. 1.]


In [3]:
colors = np.array(["red", "blue", "green", "red", "green", "blue"])


In [7]:
import numpy as np
cate=np.unique(colors)
print({cat : idx for idx,cat in enumerate(cate)})

n_samples= len(colors)
n_cate = len(cate)

np.zeros((n_samples,n_cate))

{np.str_('blue'): 0, np.str_('green'): 1, np.str_('red'): 2}


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
import numpy as np

def one_hot_encoding(data):
    
    categories = np.unique(data)
    n_samples = len(data)
    n_categories = len(categories)
    
    cat_to_idx = {cat : idx for idx , cat in enumerate(categories)}
    # creating 2d matrix of n_sample and n_categories
    one_hot = np.zeros((n_samples,n_categories))
    
    for i , value in enumerate(data):
        one_hot[i,cat_to_idx[value]]=1
    
    return one_hot,categories


    

In [13]:
encoded, categories = one_hot_encoding(colors)

print(f"Categories: {categories}")
print(f"Original: {colors}")
print(f"Encoded:\n{encoded}")

Categories: ['blue' 'green' 'red']
Original: ['red' 'blue' 'green' 'red' 'green' 'blue']
Encoded:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [17]:
import numpy as np

def confusion_matrix_values(y_true,y_pred):
    TP = np.sum((y_true==1) & (y_pred==1))
    TN = np.sum((y_true==0)& (y_pred==0))
    FP = np.sum((y_true==0) * (y_pred==1))
    FN = np.sum((y_true==1) & (y_pred==0))
    return TP,TN,FP,FN
    
def accuracy(y_true,y_pred):
    TP, TN, FP, FN = confusion_matrix_values(y_true, y_pred)
    return (TP+TN)/(TP+TN+FP+FN)

def precision(y_true,y_pred):
    TP, TN, FP, FN = confusion_matrix_values(y_true, y_pred)
    if TP + FP==0:
        return 0
    return TP/(TP+FP)

def recall(y_true,y_pred):
    TP, TN, FP, FN = confusion_matrix_values(y_true, y_pred)
    if TP+FN ==0:
        return 0
    return TP/(TP+FN)

def f1_score(y_true,y_pred):
    prec = precision(y_true,y_pred)
    rec = recall(y_true,y_pred)
    return 2*(prec*rec)/prec+rec

y_true = np.array([1, 1, 1, 0, 0, 0, 1, 0, 1, 0])
y_pred = np.array([1, 1, 0, 0, 0, 1, 1, 0, 1, 0])

print(f"Accuracy:  {accuracy(y_true, y_pred):.2f}")
print(f"Precision: {precision(y_true, y_pred):.2f}")
print(f"Recall:    {recall(y_true, y_pred):.2f}")
print(f"F1 Score:  {f1_score(y_true, y_pred):.2f}")

Accuracy:  0.80
Precision: 0.80
Recall:    0.80
F1 Score:  2.40


# Remaining Only Kmeans and Decision Tree

In [37]:
import numpy as np

cluster1 = np.random.randn(50,2) + [0,0]
cluster2 = np.random.randn(50,2) +[5,5]
cluster3 = np.random.randn(50,2) + [10,10]

X = np.concat([cluster1,cluster2,cluster3])
X.shape

(150, 2)

In [38]:
random_indices = np.random.choice(150,3,replace=False)
centroid = X[random_indices]
centroid

array([[ 5.65489433,  4.76060117],
       [-0.48929256,  1.05194748],
       [11.36308822, 11.66607811]])

In [ ]:
distances = np.zeros((150,3))
for i in range(3):
    distances[:,i] = np.linalg.norm(X-centroid[i],axis=1)
distances.mean(axis=0)

array([5.13492308, 7.28438172, 9.39459547])

In [40]:
labels = np.argmin(distances,axis=1)
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [41]:
new_centroid = np.zeros((3,2))

In [48]:
cluster_points.mean(axis=0)

array([9.93697746, 9.80740614])

In [46]:
cluster_points = X[labels==2]
new_centroid[2]=cluster_points.mean(axis=0)
cluster_points

array([[11.36308822, 11.66607811],
       [ 9.20353206, 12.52936857],
       [10.76626154,  9.18474248],
       [ 8.71759761, 10.22376266],
       [10.44524799, 11.17447495],
       [ 8.86487479, 10.55021531],
       [ 9.18296003,  9.28548504],
       [11.64473792,  8.81987358],
       [ 8.9736643 , 10.52977457],
       [10.21225153, 10.45853334],
       [ 9.28710639,  9.85648994],
       [ 8.9390107 ,  8.25612824],
       [11.58062676, 10.06365464],
       [ 9.69388844,  9.18206626],
       [10.66358655, 10.1745084 ],
       [11.46782868,  8.94464925],
       [ 9.71574043,  8.01559833],
       [10.2753883 ,  9.98852658],
       [ 8.36519639, 10.583369  ],
       [ 9.28605306, 10.7822217 ],
       [ 9.81938459,  9.34324061],
       [10.31037946,  8.25193257],
       [ 8.13733071,  9.25475242],
       [10.88114723,  9.8230507 ],
       [ 7.75922188, 10.45244547],
       [ 9.62779415,  9.16981073],
       [ 9.32231644, 10.2439315 ],
       [ 9.9488478 ,  9.77590563],
       [10.4428218 ,

In [ ]:
random_indices = np.random.choice(150,3,replace=False)
centroid = X[random_indices]
new_centroid = np.zeros((3,2))
new_centroid.shape

(3, 2)

In [8]:
def kmeans(X,k=3,max_iters=100):
    n_samples,n_features = X.shape
    random_indices = np.random.choice(n_samples,k,replace=False)
    centroid = X[random_indices]
    labels = []
    
    for iteration in range(max_iters):
        
        distances = np.zeros((n_samples,k))
        for i in range(k):
            distances[:,i] = np.linalg.norm(X - centroid[i],axis=1)
        
        labels = np.argmin(distances,axis=1)
        
        new_centroid = np.zeros((k,n_features))
        
        for i in range(k):
            cluster_points = X[labels==i]
            if len(cluster_points)>0:
                new_centroid[i] = np.mean(cluster_points,axis=0)
            else:
                new_centroid[i] = centroid[i]
                
        centroid = new_centroid
    return labels,centroid

        
    

In [11]:
cluster1 = np.random.randn(10,2) + [0,0]
cluster2 = np.random.randn(10,2) + [5,5]
cluster3 = np.random.randn(10,2) + [10,10]
X = np.concat([cluster1,cluster2,cluster3])
X.shape
labels,centroid = kmeans(X,k=3)
centroid

array([[ 4.93870493,  4.89988974],
       [10.14108163, 10.151184  ],
       [-0.40037473, -0.44505658]])

In [13]:
labels

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
def k_means_assignment(points, centroids):
    """
    Assign each point to the nearest centroid.
    """
    # Write code here
    n_samples = len(points)
    k = len(centroids)
    distance = np.zeros((n_samples,k))
    for i in range(k):
        distance[:,i] = np.linalg.norm(points - centroids[i],axis=1)
    labels = np.argmin(distance,axis=1)
    return labels

In [29]:
k_means_assignment(X,centroids=centroid)

[2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [28]:
def k_means_assignment(points, centroids):
    """
    Assign each point to the nearest centroid.
    """
    # Write code here
    assignments = []
    for point in points:
        min_dist = float("inf")
        min_idx = 0

        for idx , centroid in enumerate(centroids):
            distance = 0
            for dim in range(len(point)):
                distance+= (point[dim] - centroid[dim])**2
            if distance <min_dist:
                min_dist = distance
                min_idx = idx
        assignments.append(min_idx)
    return assignments